baseURL = "https://guangda.me"
languageCode = "en-us"
title = "Guangda Zhang's space - 无墨阁"
copyright = "Guangda Zhang"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Writings"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 4

[[menu.main]]
  name = "Categories"
  url = "/categories"
  weight = 5

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 6

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = "dracula"
    tabWidth = 4

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  DateFormat = "2006-01-02"
  description = "Welcome to my space, I will share my thoughts, life here."
  author = "Guangda Zhang"
  mainSections = ["posts"]

  [params.homeInfoParams]
    Title = "Hi, I'm Guangda Zhang"
    Content = "Welcome to my space, I will share my thoughts, life here."

  [params.assets]
    disableHLJS = true

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/inkless"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/guangda-zhang/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:hi@guangda.me"
